package com.general_hello.commands.OtherEvents;

import com.general_hello.commands.commands.Emoji.Emoji;
import net.dv8tion.jda.api.events.interaction.ButtonClickEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import org.jetbrains.annotations.NotNull;

public class OnButtonChessClick extends ListenerAdapter {
    @Override
    public void onButtonClick(@NotNull ButtonClickEvent event) {
        // users can spoof this id so be careful what you do with this
        String[] id = event.getComponentId().split(":"); // this is the custom id we specified in our button
        String authorId = id[0];
        String type = id[1];
        // When storing state like this is it is highly recommended to do some kind of verification that it was generated by you, for instance a signature or local cache

        if (!authorId.equals("0000") && !authorId.equals(event.getUser().getId())) {
            event.reply(Emoji.ERROR + "You cannot press this button").setEphemeral(true).queue();
            return;
        }

        switch (type) {
            case "bpawn":
                break;
            case "brook":
                break;
            case "bknight":
                break;
            case "bbishop":
                break;
            case "bqueen":
                break;
            case "bking":
                break;

            //white
            case "wpawn":
                break;
            case "wrook":
                break;
            case "wknight":
                break;
            case "wbishop":
                break;
            case "wqueen":
                break;
            case "wking":
                break;
            default:
                event.reply(Emoji.ERROR + "You cannot press this button").setEphemeral(true).queue();
        }
    }
}
