package com.general_hello.commands.OtherEvents;

import com.general_hello.commands.Config;
import com.general_hello.commands.commands.GroupOfGames.MiniGames.ChessStoring;
import com.general_hello.commands.commands.GroupOfGames.MiniGames.MainChessCode;
import com.general_hello.commands.commands.PrefixStoring;
import com.general_hello.commands.commands.Register.Data;
import com.github.bhlangonijr.chesslib.Board;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.Permission;
import net.dv8tion.jda.api.entities.Emoji;
import net.dv8tion.jda.api.events.interaction.ButtonClickEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.interactions.components.Button;
import net.dv8tion.jda.api.interactions.components.selections.SelectionMenu;
import org.jetbrains.annotations.NotNull;

import java.awt.*;

public class OnButtonClick extends ListenerAdapter {
    @Override
    public void onButtonClick(@NotNull ButtonClickEvent event) {
        // users can spoof this id so be careful what you do with this
        String[] id = event.getComponentId().split(":"); // this is the custom id we specified in our button
        String authorId = id[0];
        String type = id[1];
        // When storing state like this is it is highly recommended to do some kind of verification that it was generated by you, for instance a signature or local cache

        if (!authorId.equals("0000") && !authorId.equals(event.getUser().getId())) {
            event.deferEdit().queue();
            return;
        }

        switch (type)
        {
            case "nope":
            case "end":
                event.getHook().deleteOriginal().queue();
                break;
            case "user":
                event.getHook().editOriginalEmbeds(helpCrap(4, event).build()).queue();
                break;
            case "bot":
                event.getHook().editOriginalEmbeds(helpCrap(2, event).build()).queue();
                break;
            case "info":
                event.getHook().editOriginalEmbeds(helpCrap(1, event).build()).queue();
                break;
            case "mod":
                event.getHook().editOriginalEmbeds(helpCrap(3, event).build()).queue();
                break;
            case "accept":
                String arrow = "<a:arrow_1:862525611465113640>";

                event.getHook().deleteOriginal().queue();
                EmbedBuilder em = new EmbedBuilder().setTitle("Stored data").setFooter("Press the Accept button if you accept the data that will be stored!\n");
                em.setDescription("The bot stores the following data:\n" +
                        arrow + " Reads all sent messages in the server the bot is in.\n" +
                        arrow + " Reads all the messages you sent to the bot.\n" +
                        arrow + " Reads all the calls you made.\n" +
                        arrow + " Reads your user name, profile picture, nitro status, and user id.\n" +
                        arrow + " Reads all the permissions you have on that server." +
                        arrow + " Listens to everything you say during voicecalls.\n");
                event.getChannel().sendMessageEmbeds(em.build()).setActionRow(
                        Button.primary("0000:yes", "Accept").withEmoji(Emoji.fromEmote("verify", Long.parseLong("803768813110951947"), true))
                ).queue();
                break;
            case "yes":
                event.getHook().deleteOriginal().queue();
                event.getChannel().sendMessage("<a:thanks:863989523461177394> Thank you for accepting the rules and data that will be stored.").queue();
                event.getChannel().sendMessage("<a:question:863989523368247346> What do you want your username for calls to be?").queue();
                Data.progress.put(event.getUser(), 1);
                break;
            case "acceptChess":
                event.getMessage().getActionRows().get(0).updateComponent(event.getUser().getId() + ":acceptChess", event.getButton().asDisabled());
                event.getChannel().sendMessage(event.getMember().getAsMention() + " accepted the Chess challenge!\nLoading the game " + com.general_hello.commands.commands.Emoji.Emoji.LOADING).queue();
                MainChessCode.loadBoard(event);
                Board board = new Board();
                ChessStoring.userToBoard.put(event.getUser(), board);
                ChessStoring.userToBoard.put(ChessStoring.userToUser.get(event.getUser()), board);
                event.getInteraction().editButton(event.getButton().asDisabled()).queue();
                break;
            case "ownersetting":
                EmbedBuilder embedBuilder = new EmbedBuilder().setTitle(event.getUser().getName() + "'s settings for " + event.getJDA().getSelfUser().getName()).setFooter("Your settings ↔ Owner Main Page").setColor(Color.ORANGE);
                embedBuilder.setDescription("Kindly select the setting you want to change. For example, Choosing ***Prefix on DM*** will bring you to a Prefix on DM setting page where you can set your setting for Prefix On DM`");

                SelectionMenu menu = SelectionMenu.create("menu:ownersetting:" + event.getUser().getId())
                        .setPlaceholder("No setting") // shows the placeholder indicating what this menu is for
                        .setRequiredRange(1, 1) // only one can be selected
                        //.addOption("mage-arcane", "Arcane Mage")
                        .build();
                event.getMessage().editMessageEmbeds(embedBuilder.build()).setActionRow(menu).queue();
                break;
            case "modsetting":
                embedBuilder = new EmbedBuilder().setTitle(event.getUser().getName() + "'s settings for " + event.getJDA().getSelfUser().getName()).setFooter("Your settings ↔ Moderator Main Page").setColor(Color.ORANGE);
                embedBuilder.setDescription("Kindly select the setting you want to change. For example, Choosing ***Prefix on DM*** will bring you to a Prefix on DM setting page where you can set your setting for Prefix On DM`");


                menu = SelectionMenu.create("menu:modsetting:" + event.getUser().getId())
                        .setPlaceholder("Choose your setting") // shows the placeholder indicating what this menu is for
                        .setRequiredRange(1, 1) // only one can be selected
                        .addOption("XP System", "enableXP")
                        .build();

                event.getMessage().editMessageEmbeds(embedBuilder.build()).setActionRow(menu).queue();
                break;
            case "usersetting":
                embedBuilder = new EmbedBuilder().setTitle(event.getUser().getName() + "'s settings for " + event.getJDA().getSelfUser().getName()).setFooter("Your settings ↔ User Main Page").setColor(Color.ORANGE);
                embedBuilder.setDescription("Kindly select the setting you want to change. For example, Choosing ***Prefix on ping*** will bring you to a Prefix on DM setting page where you can set your setting for Prefix On DM`");

                menu = SelectionMenu.create("menu:usersetting:" + event.getUser().getId())
                        .setPlaceholder("Choose your setting") // shows the placeholder indicating what this menu is for
                        .setRequiredRange(1, 1) // only one can be selected
                        .addOption("prefixDM", "Prefix on ping")
                        .build();

                event.getMessage().editMessageEmbeds(embedBuilder.build())
                        .setActionRow(menu).queue();
                break;
            case "back":
                embedBuilder = new EmbedBuilder().setTitle(event.getUser().getName() + "'s settings for " + event.getJDA().getSelfUser().getName()).setFooter("Your settings ↔ Home Page").setColor(Color.ORANGE);
                embedBuilder.setDescription("Kindly select the category you want to change the setting of. For example, Pressing/Clicking on the button ***User*** will bring you to a setting page where you can set your user setting for `Userphone Bot`");

                boolean isMod = true;

                if (event.getMember().hasPermission(Permission.MANAGE_SERVER)) {
                    isMod = false;
                }

                boolean isOwner = true;

                if (event.getUser().getId().equals(Config.get("owner_id")) || event.getUser().getId().equals(Config.get("owner_id_partner"))) {
                    isOwner = false;
                }

                event.getMessage().editMessageEmbeds(embedBuilder.build()).setActionRow(
                        Button.primary(event.getUser().getId() + ":usersetting", "User").withEmoji(net.dv8tion.jda.api.entities.Emoji.fromEmote("user", 862895295239028756L, true)),
                        Button.primary(event.getUser().getId() + ":modsetting", "Moderation").withDisabled(isMod).withEmoji(net.dv8tion.jda.api.entities.Emoji.fromEmote("mod", 862898484041482270L, true)),
                        Button.primary(event.getUser().getId() + ":ownersetting", "Owner").withDisabled(isOwner).withEmoji(net.dv8tion.jda.api.entities.Emoji.fromEmote("babyyoda", 866105061665669140L, true))
                ).queue();
                break;

            default:
                event.reply(com.general_hello.commands.commands.Emoji.Emoji.ERROR + "You cannot press this button").setEphemeral(true).queue();
        }
    }

    public EmbedBuilder helpCrap (int number, ButtonClickEvent ctx) {
        EmbedBuilder embedBuilder = new EmbedBuilder();
        final long guildID = ctx.getGuild().getIdLong();
        String prefix = PrefixStoring.PREFIXES.computeIfAbsent(guildID, (id) -> Config.get("prefix"));

        switch (number) {
            case 1:
                embedBuilder.setTitle("Information Commands");
                embedBuilder.setColor(Color.red);
                embedBuilder.addField("1.) Profile Command","`" + prefix + "profile`", false);
                embedBuilder.addField("2.) Server Information Command","`" + prefix + "serverinfo`", false);
                embedBuilder.addField("3.) Mod Information Command ","`" + prefix + "mods`", false);

                embedBuilder.setFooter("\nType " + prefix + "help [command name] to see what they do");
                break;
            case 2:
                embedBuilder.setTitle("About the Bot Commands");
                embedBuilder.setColor(Color.blue);
                embedBuilder.addField("1.) Server List Command","`" + prefix + "serverlist`", false);
                embedBuilder.addField("2.) Server Count Command","`" + prefix + "server`", false);
                embedBuilder.addField("3.) Bug Command","`" + prefix + "bug`", false);
                embedBuilder.addField("4.) Setting Command ","`" + prefix + "settings`", false);
                embedBuilder.addField("5.) Upgrade to ***Premium*** Command ","`" + prefix + "premium`", false);
                embedBuilder.addField("6.) Set Prefix Command", "`" + prefix + "setprefix`", false);
                embedBuilder.addField("7.) Use Code Command", "`" + prefix + "code`", false);
                embedBuilder.addField("8.) Uptime Command", "`" + prefix + "uptime`", false);

                embedBuilder.setFooter("\nType " + prefix + "help [command name] to see what they do");
                break;
            case 3:
                embedBuilder.setTitle("Moderation Commands");
                embedBuilder.setColor(Color.red);
                embedBuilder.addField("1.) Kick Command", "`" + prefix + "kick`", false);
                embedBuilder.addField("2.) Ban Command", "`" + prefix + "ban`", false);
                embedBuilder.addField("3.) Mute Command", "`" + prefix + "mute`", false);
                embedBuilder.addField("4.) Deafen Command", "`" + prefix + "deafen`", false);
                embedBuilder.setFooter("\nType " + prefix + "help [command name] to see what they do");
                break;
            case 4:
                embedBuilder.setTitle("User Commands");
                embedBuilder.setColor(Color.red);
                embedBuilder.addField("1.) Register Command", "`" + prefix + "register`", false);

                embedBuilder.setFooter("\nType " + prefix + "help [command name] to see what they do");
                break;
        }
        return embedBuilder;
    }
}
